# Generated by Django 5.2 on 2025-04-17 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuariopersonalizado',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='apellido',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='numero_documento',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='tipo_documento',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
